# Your Solution

version: '3'
services:

  book_catalog:
    image: book-catalog:latest
    build: 
      context: ./book-catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
     - "8000:8000"
    environment:
    - DATABASE_URL=postgresql://db_800545486_sit22_task7_2p_user:pGGLMUOa1TJO0dta335E7Nth8mS0ZDaV@dpg-cs7ju8dumphs73a7jn7g-a.oregon-postgres.render.com/db_800545486_sit22_task7_2p    

  inventory_management:
    image: inventory-management:latest
    build: 
      context: ./inventory-management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "9000:9000" 
    environment:
     - DATABASE_URL=postgresql://db_800545486_sit22_task7_2p_user:pGGLMUOa1TJO0dta335E7Nth8mS0ZDaV@dpg-cs7ju8dumphs73a7jn7g-a.oregon-postgres.render.com/db_800545486_sit22_task7_2p
    restart: "no"