# Your Solution

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: ph2024task72p.azurecr.io/book-catalog:1
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgresql://db_800545486_sit722_part3_9x4b_user:Y66jjS5otsFclJlcaRvu0poqkOzdg4kK@dpg-cs7g74aj1k6c73fg6gdg-a.oregon-postgres.render.com/db_800545486_sit722_part3_9x4b"


apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: ph2024task72p.azurecr.io/inventory-management:1
        ports:
        - containerPort: 9000
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgresql://db_800545486_sit722_part3_9x4b_user:Y66jjS5otsFclJlcaRvu0poqkOzdg4kK@dpg-cs7g74aj1k6c73fg6gdg-a.oregon-postgres.render.com/db_800545486_sit722_part3_9x4b"


---

apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000